### ISSUE TITLE
Migration to Flutter 3.7

### ISSUE THREAD

**Issue by mny459** [rxlabz/paco#12]

**Comment by alonohana627** [comment]
I opened a PR about it.

**Comment by makayasa** [comment]
yeah there is an error after upgrade to Flutter 3.7, need to migrate the package

**Comment by alonohana627** [comment]
You could use my fork @makayasa

**Comment by galihmdev** [comment]
Hi @alonohana627 , I use your fork but seems like the opacity slider not working / can't be moved on iOS. Other slider works just fine.

**Comment by alonohana627** [comment]
> 

Im sorry but I cant help with that. I am developing for Android, Linux, Web and Windows only.
