### ISSUE TITLE
null safety ? 

### ISSUE THREAD

**Issue by yoirgla** [rxlabz/paco#14]
Here's the message a I get when installing the plugin :)

/c:/Flutter/.pub-cache/hosted/pub.dartlang.org/cyclop-0.6.1/lib/src/widgets/color_button.dart:111:29: Error: Method 'insert' cannot be called on 'OverlayState?' because it is potentially null.
 - 'OverlayState' is from 'package:flutter/src/widgets/overlay.dart' ('/c:/Flutter/packages/flutter/lib/src/widgets/overlay.dart').
Try calling using ?. instead.
    Overlay.of(rootContext).insert(pickerOverlay!);
/c:/Flutter/.pub-cache/hosted/pub.dartlang.org/cyclop-0.6.1/lib/src/widgets/eyedrop/eye_dropper_layer.dart:123:25: Error: Method 'insert' cannot be called on 'OverlayState?' because it is potentially null.
 - 'OverlayState' is from 'package:flutter/src/widgets/overlay.dart' ('/c:/Flutter/packages/flutter/lib/src/widgets/overlay.dart').
Try calling using ?. instead.
    Overlay.of(context).insert(data.eyeOverlayEntry!);

I hope it helps

**Comment by rxlabz** [comment]
I can't reproduce your error, the package is "null safe" and works fine with Dart 3.
