### ISSUE TITLE
Enable the eyedropper is not visible

### ISSUE THREAD

**Issue by Govindbetterlives** [rxlabz/paco#17]
I am using cyclop: ^0.5.2 in this version. I am rendered in "**Flutter run -d chrome --web-renderer html**"

The eye drop icon is not visible in color picker container.

![image](https://github.com/rxlabz/cyclop/assets/81243940/9d2985dc-6f75-46c9-a913-b4c37432697d)

**Comment by rxlabz** [comment]
Hi, the eyedropper can't work with the HTML web-renderer (https://github.com/flutter/flutter/issues/59072), only with CanvasKit (https://github.com/flutter/flutter/issues/42767), so it is disabled when not available.
