### ISSUE TITLE
Eye dropper can't reach outside app window

### ISSUE THREAD

**Issue by ferllings** [rxlabz/paco#18]
Hello,
Sorry if my question is stupid, I'm new to Flutter/Dart.

I've tested your example code on a MacOS app, but the Eye dropper doesn't seems to be able to move out the app window and grap a color on the desktop.

How can make the eye dropper be able to grab a color on another app?

Thanks

**Comment by rxlabz** [comment]
Hi,
indeed this is a "pure Dart" package, which only works within the Flutter app window.
To grab color from any app window or anywhere on the screen you'll need a "native plugin" for each platform.
I don't think there is one available.

**Comment by ferllings** [comment]
Thanks for your response.
