### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by remixie** [rxlabz/paco#3]
Hello. I would like to use this flutter widget inside my own project but I don't know what license this project is filed under. Please update the license for this project on Github: [https://github.com/rxlabz/cyclop/blob/master/LICENSE](https://github.com/rxlabz/cyclop/blob/master/LICENSE) 

Thank you.

**Comment by rxlabz** [comment]
Hi,
Done ! MIT licence it is.
I'll be very happy to see what you do with it if it's possible someday !
Have fun :)
