### ISSUE TITLE
Incorrect height and scrolling when in landscape

### ISSUE THREAD

**Issue by widavies** [rxlabz/paco#6]
When the device rotates into landscape mode, the picker dialog gets too high and draws a bit off screen towards the top.
Also, because the entire height can't be displayed, scrolling kicks in. However, the color grid area absorbs all scrolling motions, so the user can't scroll up or down to the close button or the hex color entry button. Possible solution would be: when a user, for example, is scrolling up on the color grid selector, when they reach the top row, then it starts scrolling the entire frame up to the title & close button, and the same for the bottom. I've also noticed that the scroll position doesn't always default to the top in this case, which is a bit confusing.

Thanks, and let me know if you need more detail or a video of this happening.

**Comment by rxlabz** [comment]
Sorry for the delay, but it's now fixed.
